id = "bend"
name = "Bend"
version = "0.1.0"
schema_version = 1
authors = ["Fabián Vega Alcota"]
description = "Bend language support: syntax highlighting, outline, snippets and `bend` diagnostics."
repository = "https://github.com/FabianVegaA/zed_bend"

[grammars.bend]
repository = "https://github.com/FabianVegaA/tree-sitter-bend"
rev = "a0a174e21a17cd0af5c62143025fb7da4e4c6c38"

[language_servers.bend]
name = "Bend"
languages = ["Bend"]
